services:
  database:
    build:
      context: ./env
      target: database
    volumes:
      - ./:/volumes/db
    ports:
      - "27017:27017"
    command: mongod

  app:
    build:
      context: ./env
      target: app
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./:/volumes/app
    working_dir: /usr/src/app
    ports:
      - "80:3000"
    command: node seeds/seed.js
    command: node app.js
    environment:
      - DB_HOST=database:27017
    restart: always